### ISSUE TITLE
readme step is confusing

### ISSUE THREAD

**Issue by tmills** [tmills/ctakes-docker#12]
Hi Matthew (@MatthewVita), I'm a bit unclear on one of the new instructions in the README. The first step under running under collection reader is to edit docker-fast-dictionary.xml to change the import, but there is no import by default in that file, so that could be confusing. Can we try to clarify what we want there?

**Comment by MatthewVita** [comment]
Hi Tim,

Oops. I believe it should be https://github.com/tmills/ctakes-docker/pull/13

Do you think there is a way we can make this a relative path?

Thanks,
Mattew

**Comment by tmills** [comment]
I guess I still don't see how that would be called. If you run with:
```desc/localDeploymentDescriptor.xml```
it calls out to remoteFull.xml (which in turn references docker-fast-dictionary.xml locally), and if you run with:
```desc/localDeploymentDescriptorNoDeid.xml```
it calls out to remoteNoDeid.xml, which already references docker-fast-dictionary.xml correctly.

I think we actually might be able to just delete remoteFastDescriptor.xml?

**Comment by MatthewVita** [comment]
Okay Tim,

This is one of those classic "just trying to getting it working and noting down the steps situations.... and it turns out one of the steps actually has no effect!".

I believe you are correct that `remoteFastDescriptor.xml` is simply not used in any meaningful way. The only hard reference to it is in https://github.com/tmills/ctakes-docker/blob/67ed20f10331c40cefaf9c557999e4365ced8f9d/src/main/java/GenerateDescriptors.java#L12 but that's more for just wiring it into the context if I'm looking at it correctly.

I will put together a PR today or tomorrow to remove the file.

Thanks,
Matthew

**Comment by tmills** [comment]
I've definitely been there! Thanks for confirming, and let me know when you get a chance if your test works.

**Comment by MatthewVita** [comment]
Okay sir,

The PR is testing well without de-id. I tested with GUI as well as the collection reader. If you could, please make sure the PR doesn't break your mist stuff: https://github.com/tmills/ctakes-docker/pull/14

Ready to go!

Thanks,
Matthew
